version: "3.7"

services:
### PHP Container #########################################
  decorator:
    container_name: app_decorator
    hostname: decorator
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html/app
    volumes:
      - ./var/www/html/app
    depends_on:
      - decoratordb
      - decoratorredis

  ### NGINX Container #########################################
  nginx:
    container_name: app_nginx
    hostname: nginx
    image: nginx:1.17
    restart: unless-stopped
    depends_on:
      - decorator
    ports:
      - 5000:80
    volumes:
      - ./var/www/html/app
      - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf

### POSTGRESS Container #########################################
  decoratordb:
    container_name: app_decoratordb
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: decorator
      POSTGRES_USER: decorator-user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    ports:
      - "54321:5432"

### Redis Container #########################################
  decoratorredis:
    container_name: app_decoratorredis
    hostname: redis
    image: redis:5.0
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
